name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
        name: NPM Install
      - run: npm run prepublish
        name: Build & Prepublish
      - run: cd dist/ngx-crumbs && npm publish
        name: Publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
